# Generated by Django 3.0.8 on 2021-04-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pagina de Inicio',
                'verbose_name_plural': 'Pagina de Inicio',
                'ordering': ['nombre'],
            },
        ),
    ]
